# SPRING PROPERTIES
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gro
    username: user
    password: user
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  profiles:
    include:
      'query'

# JWT : JSON WEB TOKEN PROPERTIES
jwt:
  header: Authorization
  secret: password
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
      
exception:
  rpi-component-not-found: Component with supplied id was not found
  
  
twilio:
  account:
    sid: AC43c54b1d3ecf7b22f1e10abb5d517c73
    auth_token: 0b08922d64697cf6dd7a0b500f58e937
  phone:
    inbound: +12482434260
    outbound: +12483219021 